// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Archives: typeof import('./components/Archives/index.vue')['default']
    ArticleCard: typeof import('./components/Slots/ArticleCard/index.vue')['default']
    ArticleItem: typeof import('./components/Home/MainFeature/ArticleItem.vue')['default']
    BackTop: typeof import('./components/BackTop.vue')['default']
    CardSkelenton: typeof import('./components/Slots/Skeleton/cardSkelenton.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Home: typeof import('./components/Home/index.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IEpArrowUpBold: typeof import('~icons/ep/arrow-up-bold')['default']
    IEpChatDotSquare: typeof import('~icons/ep/chat-dot-square')['default']
    IEpCollection: typeof import('~icons/ep/collection')['default']
    IEpCollectionTag: typeof import('~icons/ep/collection-tag')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpFinished: typeof import('~icons/ep/finished')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMore: typeof import('~icons/ep/more')['default']
    IEpPriceTag: typeof import('~icons/ep/price-tag')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpTimer: typeof import('~icons/ep/timer')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpView: typeof import('~icons/ep/view')['default']
    Links: typeof import('./components/Links/index.vue')['default']
    MainFeature: typeof import('./components/Home/MainFeature/index.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    PagesModule: typeof import('./components/Slots/PagesModule/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tags: typeof import('./components/Tags/index.vue')['default']
    TopFeature: typeof import('./components/Home/TopFeature/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
